# .travis.yml

dist: focal

language: node_js

node_js:
    - 20
    - 22

install:
    - corepack enable
    - pnpm install --frozen-lockfile

script:
    - pnpm test -- --coverage

after_script:
    - pnpm coverage:report
